
exp_name: debug
method: TASC
gpu: 5,
lightning: true
logger: DEBUG
logger_console: false
amp: true


method_args:

  source: true
  target: true

  fixed_weights: True  #

  ce_prob_temp: 0.02  # 0.02
  text_temp: 0.02  # 0.02
  ent_temp: 0.01
  metric_temp: 0.01

  ent_thr: 0.3
  n_keep_status: 5  #

  target_classnames: "discovered"  # "discovered", "gt-target", "gt-source"

  loss_s_ce: 1.0
  loss_t_im_ent: 1.0
  loss_t_im_div: 0.6

  templates_sampling_rate: 1.0
  templates_type: ensemble

  TASC:
    num_clusters_dict:
      office: 100
      officehome: 100
      visda: 100
      domainnet: 400
    n_inner: 20
    K_s: 300
    K_beam: 1


dataset:
  name: office
  task: dw
  shared: 10
  source_private: 10
  target_private: 11
  balanced: true
  batchsize: 32
  val_batchsize: 64
  num_workers: 4
  val_source: false
  augmentation: ['clip-randomcrop', 'clip-strong_2']


model:
  lora_r: 8
  lora_r_t: 8
  name: ViT-B/16


optimizer:
  backbone_lr: 0.0001
  momentum: 0.9
  weight_decay: 0.0005


lr_schedule:
  lr_cfg:
    gamma: 10
    power: 0.75
  max_iter: 10000
  type: inv
  warmup_iter: 50
  warmup_min_lr: 1.0e-05
  warmup_type: linear


control:
  interval: 500
  log_interval: 100
  max_iter: 10000
  save_model: false
  seed:
    flag: false
    seed: 2022


test:
  none: none


train:
  none: none
